<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2025/07/16 09:15:18

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'pgsql:host=localhost;dbname=advanced_form',
  'username' => 'postgres',
  'password' => '123',
  'name' => 'doctrine',
)),);
